-- AlterTable
ALTER TABLE `orden` ADD COLUMN `abonado` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `estadoPago` VARCHAR(191) NOT NULL DEFAULT 'INCOMPLETO',
    ADD COLUMN `faltante` DOUBLE NOT NULL DEFAULT 0;
